"""Example: basic global map.

Run:
    python examples/02_basic_map.py
"""

import numpy as np
import pandas as pd

from plotting_joseph import plot_map

# ---------------------------------------------------------------------------
# 1. Build a grid lookup table ..._gridSampling_<res>_kN.parquet
# ---------------------------------------------------------------------------
# A real lookup is generated by your gridding pipeline. Here we make a small
# stand-in on a 2-degree grid for demonstration.
n_lat, n_lon = 20, 30
grid_sampling = 12.5 / 111.0  # ~12.5 km in degrees

pc = []
pid = 0
for r in range(n_lat):
    for c in range(n_lon):
        if pid % 4 == 0:  # a subset of locations
            pc.append({"location_id": pid, "pixel_id": pid})
        pid += 1
lookup = pd.DataFrame(pc)
lookup.to_parquet("lookup_tables/gridSampling_0.1126_k1.parquet", index=False)

# ---------------------------------------------------------------------------
# 2. Map data: one value per location
# ---------------------------------------------------------------------------
rng = np.random.RandomState(42)
data = pd.DataFrame(
    {"location_id": lookup["location_id"], "backscatter40": rng.normal(size=len(lookup))}
)

# ---------------------------------------------------------------------------
# 3. Plot
# ---------------------------------------------------------------------------
fig = plot_map(
    data=data,
    var="backscatter40",
    lookuptable_path="lookup_tables/gridSampling_0.1126_k1.parquet",
    title="Synthetic Global Backscatter",
    grid_sampling=grid_sampling,
    plot_robust=(2, 98),
    save_path="figures/global_map.png",
)
print("Saved figure to ./figures/global_map.png")
